/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PreviewDarkRouteImport } from './routes/preview-dark'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemasIndexRouteImport } from './routes/temas.index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VipSlugRouteImport } from './routes/vip.$slug'
import { Route as TemasSlugRouteImport } from './routes/temas.$slug'
import { Route as SuperadminMetricasRouteImport } from './routes/superadmin.metricas'
import { Route as SuperadminLojasRouteImport } from './routes/superadmin.lojas'
import { Route as SuperadminClientesRouteImport } from './routes/superadmin.clientes'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as HooksCleanupOrphanStoresRouteImport } from './routes/hooks/cleanup-orphan-stores'
import { Route as HooksCartRecoveryRouteImport } from './routes/hooks/cart-recovery'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiVirtualTryOnRouteImport } from './routes/api/virtual-try-on'
import { Route as AdminVendasRouteImport } from './routes/admin.vendas'
import { Route as AdminTemasRouteImport } from './routes/admin.temas'
import { Route as AdminPlanoRouteImport } from './routes/admin.plano'
import { Route as AdminPersonalizarLojaRouteImport } from './routes/admin.personalizar-loja'
import { Route as AdminPerguntasRouteImport } from './routes/admin.perguntas'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminHomeVideoRouteImport } from './routes/admin.home-video'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEstatisticasRouteImport } from './routes/admin.estatisticas'
import { Route as AdminDescontosRouteImport } from './routes/admin.descontos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as LojaSlugIndexRouteImport } from './routes/loja.$slug.index'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminMarketingIndexRouteImport } from './routes/admin.marketing.index'
import { Route as AdminEstatisticasIndexRouteImport } from './routes/admin.estatisticas.index'
import { Route as AdminConfiguracoesIndexRouteImport } from './routes/admin.configuracoes.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LojaSlugWishlistRouteImport } from './routes/loja.$slug.wishlist'
import { Route as LojaSlugSobreRouteImport } from './routes/loja.$slug.sobre'
import { Route as LojaSlugRastreioRouteImport } from './routes/loja.$slug.rastreio'
import { Route as LojaSlugBuscaRouteImport } from './routes/loja.$slug.busca'
import { Route as FeedSlugMetaDotxmlRouteImport } from './routes/feed.$slug.meta[.]xml'
import { Route as ApiPublicHostDebugRouteImport } from './routes/api/public/host-debug'
import { Route as AdminTemasSucessoRouteImport } from './routes/admin.temas.sucesso'
import { Route as AdminProdutosTabelaPrecosRouteImport } from './routes/admin.produtos.tabela-precos'
import { Route as AdminProdutosCategoriasRouteImport } from './routes/admin.produtos.categorias'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as AdminMarketingVideoCommerceRouteImport } from './routes/admin.marketing.video-commerce'
import { Route as AdminMarketingPerguntasAvaliacoesRouteImport } from './routes/admin.marketing.perguntas-avaliacoes'
import { Route as AdminMarketingGrupoVipRouteImport } from './routes/admin.marketing.grupo-vip'
import { Route as AdminMarketingCompreJuntoRouteImport } from './routes/admin.marketing.compre-junto'
import { Route as AdminMarketingCapturaLeadsRouteImport } from './routes/admin.marketing.captura-leads'
import { Route as AdminLojaRedesSociaisRouteImport } from './routes/admin.loja.redes-sociais'
import { Route as AdminLojaPaginasRouteImport } from './routes/admin.loja.paginas'
import { Route as AdminLojaMenusRouteImport } from './routes/admin.loja.menus'
import { Route as AdminLojaFiltrosRouteImport } from './routes/admin.loja.filtros'
import { Route as AdminEstatisticasVisitasRouteImport } from './routes/admin.estatisticas.visitas'
import { Route as AdminEstatisticasVendasRouteImport } from './routes/admin.estatisticas.vendas'
import { Route as AdminEstatisticasTempoRealRouteImport } from './routes/admin.estatisticas.tempo-real'
import { Route as AdminEstatisticasProdutosRouteImport } from './routes/admin.estatisticas.produtos'
import { Route as AdminDescontosPromocoesRouteImport } from './routes/admin.descontos.promocoes'
import { Route as AdminDescontosFreteGratisRouteImport } from './routes/admin.descontos.frete-gratis'
import { Route as AdminDescontosCuponsRouteImport } from './routes/admin.descontos.cupons'
import { Route as AdminConfiguracoesWhatsappRouteImport } from './routes/admin.configuracoes.whatsapp'
import { Route as AdminConfiguracoesUsuariosRouteImport } from './routes/admin.configuracoes.usuarios'
import { Route as AdminConfiguracoesPoliticasRouteImport } from './routes/admin.configuracoes.politicas'
import { Route as AdminConfiguracoesPagamentosRouteImport } from './routes/admin.configuracoes.pagamentos'
import { Route as AdminConfiguracoesEquipeRouteImport } from './routes/admin.configuracoes.equipe'
import { Route as AdminConfiguracoesDominiosRouteImport } from './routes/admin.configuracoes.dominios'
import { Route as AdminConfiguracoesContatoRouteImport } from './routes/admin.configuracoes.contato'
import { Route as AdminClientesLeadsRouteImport } from './routes/admin.clientes.leads'
import { Route as AdminClientesAvaliacoesRouteImport } from './routes/admin.clientes.avaliacoes'
import { Route as AdminLojaLayoutIndexRouteImport } from './routes/admin.loja.layout.index'
import { Route as LovableEmailTransactionalSendInternalRouteImport } from './routes/lovable/email/transactional/send-internal'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LojaSlugProdutoProductSlugRouteImport } from './routes/loja.$slug.produto.$productSlug'
import { Route as LojaSlugPaginaPageSlugRouteImport } from './routes/loja.$slug.pagina.$pageSlug'
import { Route as LojaSlugCategoriaCategorySlugRouteImport } from './routes/loja.$slug.categoria.$categorySlug'
import { Route as AdminLojaLayoutEditarRouteImport } from './routes/admin.loja.layout.editar'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDarkRoute = PreviewDarkRouteImport.update({
  id: '/preview-dark',
  path: '/preview-dark',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasIndexRoute = TemasIndexRouteImport.update({
  id: '/temas/',
  path: '/temas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VipSlugRoute = VipSlugRouteImport.update({
  id: '/vip/$slug',
  path: '/vip/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasSlugRoute = TemasSlugRouteImport.update({
  id: '/temas/$slug',
  path: '/temas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminMetricasRoute = SuperadminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLojasRoute = SuperadminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminClientesRoute = SuperadminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => SuperadminRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksCleanupOrphanStoresRoute =
  HooksCleanupOrphanStoresRouteImport.update({
    id: '/hooks/cleanup-orphan-stores',
    path: '/hooks/cleanup-orphan-stores',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksCartRecoveryRoute = HooksCartRecoveryRouteImport.update({
  id: '/hooks/cart-recovery',
  path: '/hooks/cart-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVirtualTryOnRoute = ApiVirtualTryOnRouteImport.update({
  id: '/api/virtual-try-on',
  path: '/api/virtual-try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemasRoute = AdminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanoRoute = AdminPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonalizarLojaRoute = AdminPersonalizarLojaRouteImport.update({
  id: '/personalizar-loja',
  path: '/personalizar-loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerguntasRoute = AdminPerguntasRouteImport.update({
  id: '/perguntas',
  path: '/perguntas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeVideoRoute = AdminHomeVideoRouteImport.update({
  id: '/home-video',
  path: '/home-video',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstatisticasRoute = AdminEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDescontosRoute = AdminDescontosRouteImport.update({
  id: '/descontos',
  path: '/descontos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingIndexRoute = AdminMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminEstatisticasIndexRoute = AdminEstatisticasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEstatisticasRoute,
} as any)
const AdminConfiguracoesIndexRoute = AdminConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConfiguracoesRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugWishlistRoute = LojaSlugWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugSobreRoute = LojaSlugSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugRastreioRoute = LojaSlugRastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugBuscaRoute = LojaSlugBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => LojaSlugRoute,
} as any)
const FeedSlugMetaDotxmlRoute = FeedSlugMetaDotxmlRouteImport.update({
  id: '/feed/$slug/meta.xml',
  path: '/feed/$slug/meta.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHostDebugRoute = ApiPublicHostDebugRouteImport.update({
  id: '/api/public/host-debug',
  path: '/api/public/host-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemasSucessoRoute = AdminTemasSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => AdminTemasRoute,
} as any)
const AdminProdutosTabelaPrecosRoute =
  AdminProdutosTabelaPrecosRouteImport.update({
    id: '/produtos/tabela-precos',
    path: '/produtos/tabela-precos',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProdutosCategoriasRoute = AdminProdutosCategoriasRouteImport.update({
  id: '/produtos/categorias',
  path: '/produtos/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingVideoCommerceRoute =
  AdminMarketingVideoCommerceRouteImport.update({
    id: '/video-commerce',
    path: '/video-commerce',
    getParentRoute: () => AdminMarketingRoute,
  } as any)
const AdminMarketingPerguntasAvaliacoesRoute =
  AdminMarketingPerguntasAvaliacoesRouteImport.update({
    id: '/perguntas-avaliacoes',
    path: '/perguntas-avaliacoes',
    getParentRoute: () => AdminMarketingRoute,
  } as any)
const AdminMarketingGrupoVipRoute = AdminMarketingGrupoVipRouteImport.update({
  id: '/grupo-vip',
  path: '/grupo-vip',
  getParentRoute: () => AdminMarketingRoute,
} as any)
const AdminMarketingCompreJuntoRoute =
  AdminMarketingCompreJuntoRouteImport.update({
    id: '/compre-junto',
    path: '/compre-junto',
    getParentRoute: () => AdminMarketingRoute,
  } as any)
const AdminMarketingCapturaLeadsRoute =
  AdminMarketingCapturaLeadsRouteImport.update({
    id: '/captura-leads',
    path: '/captura-leads',
    getParentRoute: () => AdminMarketingRoute,
  } as any)
const AdminLojaRedesSociaisRoute = AdminLojaRedesSociaisRouteImport.update({
  id: '/loja/redes-sociais',
  path: '/loja/redes-sociais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaPaginasRoute = AdminLojaPaginasRouteImport.update({
  id: '/loja/paginas',
  path: '/loja/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaMenusRoute = AdminLojaMenusRouteImport.update({
  id: '/loja/menus',
  path: '/loja/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaFiltrosRoute = AdminLojaFiltrosRouteImport.update({
  id: '/loja/filtros',
  path: '/loja/filtros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstatisticasVisitasRoute =
  AdminEstatisticasVisitasRouteImport.update({
    id: '/visitas',
    path: '/visitas',
    getParentRoute: () => AdminEstatisticasRoute,
  } as any)
const AdminEstatisticasVendasRoute = AdminEstatisticasVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminEstatisticasRoute,
} as any)
const AdminEstatisticasTempoRealRoute =
  AdminEstatisticasTempoRealRouteImport.update({
    id: '/tempo-real',
    path: '/tempo-real',
    getParentRoute: () => AdminEstatisticasRoute,
  } as any)
const AdminEstatisticasProdutosRoute =
  AdminEstatisticasProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AdminEstatisticasRoute,
  } as any)
const AdminDescontosPromocoesRoute = AdminDescontosPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AdminDescontosRoute,
} as any)
const AdminDescontosFreteGratisRoute =
  AdminDescontosFreteGratisRouteImport.update({
    id: '/frete-gratis',
    path: '/frete-gratis',
    getParentRoute: () => AdminDescontosRoute,
  } as any)
const AdminDescontosCuponsRoute = AdminDescontosCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminDescontosRoute,
} as any)
const AdminConfiguracoesWhatsappRoute =
  AdminConfiguracoesWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesUsuariosRoute =
  AdminConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesPoliticasRoute =
  AdminConfiguracoesPoliticasRouteImport.update({
    id: '/politicas',
    path: '/politicas',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesPagamentosRoute =
  AdminConfiguracoesPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesEquipeRoute =
  AdminConfiguracoesEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesDominiosRoute =
  AdminConfiguracoesDominiosRouteImport.update({
    id: '/dominios',
    path: '/dominios',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminConfiguracoesContatoRoute =
  AdminConfiguracoesContatoRouteImport.update({
    id: '/contato',
    path: '/contato',
    getParentRoute: () => AdminConfiguracoesRoute,
  } as any)
const AdminClientesLeadsRoute = AdminClientesLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminClientesRoute,
} as any)
const AdminClientesAvaliacoesRoute = AdminClientesAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminClientesRoute,
} as any)
const AdminLojaLayoutIndexRoute = AdminLojaLayoutIndexRouteImport.update({
  id: '/loja/layout/',
  path: '/loja/layout/',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendInternalRoute =
  LovableEmailTransactionalSendInternalRouteImport.update({
    id: '/lovable/email/transactional/send-internal',
    path: '/lovable/email/transactional/send-internal',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugProdutoProductSlugRoute =
  LojaSlugProdutoProductSlugRouteImport.update({
    id: '/produto/$productSlug',
    path: '/produto/$productSlug',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const LojaSlugPaginaPageSlugRoute = LojaSlugPaginaPageSlugRouteImport.update({
  id: '/pagina/$pageSlug',
  path: '/pagina/$pageSlug',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugCategoriaCategorySlugRoute =
  LojaSlugCategoriaCategorySlugRouteImport.update({
    id: '/categoria/$categorySlug',
    path: '/categoria/$categorySlug',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const AdminLojaLayoutEditarRoute = AdminLojaLayoutEditarRouteImport.update({
  id: '/loja/layout/editar',
  path: '/loja/layout/editar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/preview-dark': typeof PreviewDarkRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/descontos': typeof AdminDescontosRouteWithChildren
  '/admin/estatisticas': typeof AdminEstatisticasRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/home-video': typeof AdminHomeVideoRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perguntas': typeof AdminPerguntasRoute
  '/admin/personalizar-loja': typeof AdminPersonalizarLojaRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/admin/vendas': typeof AdminVendasRoute
  '/api/virtual-try-on': typeof ApiVirtualTryOnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/cart-recovery': typeof HooksCartRecoveryRoute
  '/hooks/cleanup-orphan-stores': typeof HooksCleanupOrphanStoresRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/superadmin/clientes': typeof SuperadminClientesRoute
  '/superadmin/lojas': typeof SuperadminLojasRoute
  '/superadmin/metricas': typeof SuperadminMetricasRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/vip/$slug': typeof VipSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/temas/': typeof TemasIndexRoute
  '/admin/clientes/avaliacoes': typeof AdminClientesAvaliacoesRoute
  '/admin/clientes/leads': typeof AdminClientesLeadsRoute
  '/admin/configuracoes/contato': typeof AdminConfiguracoesContatoRoute
  '/admin/configuracoes/dominios': typeof AdminConfiguracoesDominiosRoute
  '/admin/configuracoes/equipe': typeof AdminConfiguracoesEquipeRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/politicas': typeof AdminConfiguracoesPoliticasRoute
  '/admin/configuracoes/usuarios': typeof AdminConfiguracoesUsuariosRoute
  '/admin/configuracoes/whatsapp': typeof AdminConfiguracoesWhatsappRoute
  '/admin/descontos/cupons': typeof AdminDescontosCuponsRoute
  '/admin/descontos/frete-gratis': typeof AdminDescontosFreteGratisRoute
  '/admin/descontos/promocoes': typeof AdminDescontosPromocoesRoute
  '/admin/estatisticas/produtos': typeof AdminEstatisticasProdutosRoute
  '/admin/estatisticas/tempo-real': typeof AdminEstatisticasTempoRealRoute
  '/admin/estatisticas/vendas': typeof AdminEstatisticasVendasRoute
  '/admin/estatisticas/visitas': typeof AdminEstatisticasVisitasRoute
  '/admin/loja/filtros': typeof AdminLojaFiltrosRoute
  '/admin/loja/menus': typeof AdminLojaMenusRoute
  '/admin/loja/paginas': typeof AdminLojaPaginasRoute
  '/admin/loja/redes-sociais': typeof AdminLojaRedesSociaisRoute
  '/admin/marketing/captura-leads': typeof AdminMarketingCapturaLeadsRoute
  '/admin/marketing/compre-junto': typeof AdminMarketingCompreJuntoRoute
  '/admin/marketing/grupo-vip': typeof AdminMarketingGrupoVipRoute
  '/admin/marketing/perguntas-avaliacoes': typeof AdminMarketingPerguntasAvaliacoesRoute
  '/admin/marketing/video-commerce': typeof AdminMarketingVideoCommerceRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/categorias': typeof AdminProdutosCategoriasRoute
  '/admin/produtos/tabela-precos': typeof AdminProdutosTabelaPrecosRoute
  '/admin/temas/sucesso': typeof AdminTemasSucessoRoute
  '/api/public/host-debug': typeof ApiPublicHostDebugRoute
  '/feed/$slug/meta.xml': typeof FeedSlugMetaDotxmlRoute
  '/loja/$slug/busca': typeof LojaSlugBuscaRoute
  '/loja/$slug/rastreio': typeof LojaSlugRastreioRoute
  '/loja/$slug/sobre': typeof LojaSlugSobreRoute
  '/loja/$slug/wishlist': typeof LojaSlugWishlistRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/estatisticas/': typeof AdminEstatisticasIndexRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/admin/loja/layout/editar': typeof AdminLojaLayoutEditarRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRoute
  '/loja/$slug/pagina/$pageSlug': typeof LojaSlugPaginaPageSlugRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/lovable/email/transactional/send-internal': typeof LovableEmailTransactionalSendInternalRoute
  '/admin/loja/layout/': typeof AdminLojaLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/preview-dark': typeof PreviewDarkRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/descontos': typeof AdminDescontosRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/home-video': typeof AdminHomeVideoRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perguntas': typeof AdminPerguntasRoute
  '/admin/personalizar-loja': typeof AdminPersonalizarLojaRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/admin/vendas': typeof AdminVendasRoute
  '/api/virtual-try-on': typeof ApiVirtualTryOnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/cart-recovery': typeof HooksCartRecoveryRoute
  '/hooks/cleanup-orphan-stores': typeof HooksCleanupOrphanStoresRoute
  '/superadmin/clientes': typeof SuperadminClientesRoute
  '/superadmin/lojas': typeof SuperadminLojasRoute
  '/superadmin/metricas': typeof SuperadminMetricasRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/vip/$slug': typeof VipSlugRoute
  '/admin': typeof AdminIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/temas': typeof TemasIndexRoute
  '/admin/clientes/avaliacoes': typeof AdminClientesAvaliacoesRoute
  '/admin/clientes/leads': typeof AdminClientesLeadsRoute
  '/admin/configuracoes/contato': typeof AdminConfiguracoesContatoRoute
  '/admin/configuracoes/dominios': typeof AdminConfiguracoesDominiosRoute
  '/admin/configuracoes/equipe': typeof AdminConfiguracoesEquipeRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/politicas': typeof AdminConfiguracoesPoliticasRoute
  '/admin/configuracoes/usuarios': typeof AdminConfiguracoesUsuariosRoute
  '/admin/configuracoes/whatsapp': typeof AdminConfiguracoesWhatsappRoute
  '/admin/descontos/cupons': typeof AdminDescontosCuponsRoute
  '/admin/descontos/frete-gratis': typeof AdminDescontosFreteGratisRoute
  '/admin/descontos/promocoes': typeof AdminDescontosPromocoesRoute
  '/admin/estatisticas/produtos': typeof AdminEstatisticasProdutosRoute
  '/admin/estatisticas/tempo-real': typeof AdminEstatisticasTempoRealRoute
  '/admin/estatisticas/vendas': typeof AdminEstatisticasVendasRoute
  '/admin/estatisticas/visitas': typeof AdminEstatisticasVisitasRoute
  '/admin/loja/filtros': typeof AdminLojaFiltrosRoute
  '/admin/loja/menus': typeof AdminLojaMenusRoute
  '/admin/loja/paginas': typeof AdminLojaPaginasRoute
  '/admin/loja/redes-sociais': typeof AdminLojaRedesSociaisRoute
  '/admin/marketing/captura-leads': typeof AdminMarketingCapturaLeadsRoute
  '/admin/marketing/compre-junto': typeof AdminMarketingCompreJuntoRoute
  '/admin/marketing/grupo-vip': typeof AdminMarketingGrupoVipRoute
  '/admin/marketing/perguntas-avaliacoes': typeof AdminMarketingPerguntasAvaliacoesRoute
  '/admin/marketing/video-commerce': typeof AdminMarketingVideoCommerceRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/categorias': typeof AdminProdutosCategoriasRoute
  '/admin/produtos/tabela-precos': typeof AdminProdutosTabelaPrecosRoute
  '/admin/temas/sucesso': typeof AdminTemasSucessoRoute
  '/api/public/host-debug': typeof ApiPublicHostDebugRoute
  '/feed/$slug/meta.xml': typeof FeedSlugMetaDotxmlRoute
  '/loja/$slug/busca': typeof LojaSlugBuscaRoute
  '/loja/$slug/rastreio': typeof LojaSlugRastreioRoute
  '/loja/$slug/sobre': typeof LojaSlugSobreRoute
  '/loja/$slug/wishlist': typeof LojaSlugWishlistRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/configuracoes': typeof AdminConfiguracoesIndexRoute
  '/admin/estatisticas': typeof AdminEstatisticasIndexRoute
  '/admin/marketing': typeof AdminMarketingIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/admin/loja/layout/editar': typeof AdminLojaLayoutEditarRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRoute
  '/loja/$slug/pagina/$pageSlug': typeof LojaSlugPaginaPageSlugRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/lovable/email/transactional/send-internal': typeof LovableEmailTransactionalSendInternalRoute
  '/admin/loja/layout': typeof AdminLojaLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/preview-dark': typeof PreviewDarkRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/descontos': typeof AdminDescontosRouteWithChildren
  '/admin/estatisticas': typeof AdminEstatisticasRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/home-video': typeof AdminHomeVideoRoute
  '/admin/marketing': typeof AdminMarketingRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/perguntas': typeof AdminPerguntasRoute
  '/admin/personalizar-loja': typeof AdminPersonalizarLojaRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/temas': typeof AdminTemasRouteWithChildren
  '/admin/vendas': typeof AdminVendasRoute
  '/api/virtual-try-on': typeof ApiVirtualTryOnRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/hooks/cart-recovery': typeof HooksCartRecoveryRoute
  '/hooks/cleanup-orphan-stores': typeof HooksCleanupOrphanStoresRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/superadmin/clientes': typeof SuperadminClientesRoute
  '/superadmin/lojas': typeof SuperadminLojasRoute
  '/superadmin/metricas': typeof SuperadminMetricasRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/vip/$slug': typeof VipSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/temas/': typeof TemasIndexRoute
  '/admin/clientes/avaliacoes': typeof AdminClientesAvaliacoesRoute
  '/admin/clientes/leads': typeof AdminClientesLeadsRoute
  '/admin/configuracoes/contato': typeof AdminConfiguracoesContatoRoute
  '/admin/configuracoes/dominios': typeof AdminConfiguracoesDominiosRoute
  '/admin/configuracoes/equipe': typeof AdminConfiguracoesEquipeRoute
  '/admin/configuracoes/pagamentos': typeof AdminConfiguracoesPagamentosRoute
  '/admin/configuracoes/politicas': typeof AdminConfiguracoesPoliticasRoute
  '/admin/configuracoes/usuarios': typeof AdminConfiguracoesUsuariosRoute
  '/admin/configuracoes/whatsapp': typeof AdminConfiguracoesWhatsappRoute
  '/admin/descontos/cupons': typeof AdminDescontosCuponsRoute
  '/admin/descontos/frete-gratis': typeof AdminDescontosFreteGratisRoute
  '/admin/descontos/promocoes': typeof AdminDescontosPromocoesRoute
  '/admin/estatisticas/produtos': typeof AdminEstatisticasProdutosRoute
  '/admin/estatisticas/tempo-real': typeof AdminEstatisticasTempoRealRoute
  '/admin/estatisticas/vendas': typeof AdminEstatisticasVendasRoute
  '/admin/estatisticas/visitas': typeof AdminEstatisticasVisitasRoute
  '/admin/loja/filtros': typeof AdminLojaFiltrosRoute
  '/admin/loja/menus': typeof AdminLojaMenusRoute
  '/admin/loja/paginas': typeof AdminLojaPaginasRoute
  '/admin/loja/redes-sociais': typeof AdminLojaRedesSociaisRoute
  '/admin/marketing/captura-leads': typeof AdminMarketingCapturaLeadsRoute
  '/admin/marketing/compre-junto': typeof AdminMarketingCompreJuntoRoute
  '/admin/marketing/grupo-vip': typeof AdminMarketingGrupoVipRoute
  '/admin/marketing/perguntas-avaliacoes': typeof AdminMarketingPerguntasAvaliacoesRoute
  '/admin/marketing/video-commerce': typeof AdminMarketingVideoCommerceRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/categorias': typeof AdminProdutosCategoriasRoute
  '/admin/produtos/tabela-precos': typeof AdminProdutosTabelaPrecosRoute
  '/admin/temas/sucesso': typeof AdminTemasSucessoRoute
  '/api/public/host-debug': typeof ApiPublicHostDebugRoute
  '/feed/$slug/meta.xml': typeof FeedSlugMetaDotxmlRoute
  '/loja/$slug/busca': typeof LojaSlugBuscaRoute
  '/loja/$slug/rastreio': typeof LojaSlugRastreioRoute
  '/loja/$slug/sobre': typeof LojaSlugSobreRoute
  '/loja/$slug/wishlist': typeof LojaSlugWishlistRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/estatisticas/': typeof AdminEstatisticasIndexRoute
  '/admin/marketing/': typeof AdminMarketingIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/admin/loja/layout/editar': typeof AdminLojaLayoutEditarRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRoute
  '/loja/$slug/pagina/$pageSlug': typeof LojaSlugPaginaPageSlugRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/lovable/email/transactional/send-internal': typeof LovableEmailTransactionalSendInternalRoute
  '/admin/loja/layout/': typeof AdminLojaLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/funcionalidades'
    | '/login'
    | '/painel'
    | '/precos'
    | '/preview-dark'
    | '/privacidade'
    | '/recuperar-senha'
    | '/reset-password'
    | '/superadmin'
    | '/termos'
    | '/unsubscribe'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/descontos'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/home-video'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/perguntas'
    | '/admin/personalizar-loja'
    | '/admin/plano'
    | '/admin/temas'
    | '/admin/vendas'
    | '/api/virtual-try-on'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/hooks/cart-recovery'
    | '/hooks/cleanup-orphan-stores'
    | '/loja/$slug'
    | '/superadmin/clientes'
    | '/superadmin/lojas'
    | '/superadmin/metricas'
    | '/temas/$slug'
    | '/vip/$slug'
    | '/admin/'
    | '/superadmin/'
    | '/temas/'
    | '/admin/clientes/avaliacoes'
    | '/admin/clientes/leads'
    | '/admin/configuracoes/contato'
    | '/admin/configuracoes/dominios'
    | '/admin/configuracoes/equipe'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/politicas'
    | '/admin/configuracoes/usuarios'
    | '/admin/configuracoes/whatsapp'
    | '/admin/descontos/cupons'
    | '/admin/descontos/frete-gratis'
    | '/admin/descontos/promocoes'
    | '/admin/estatisticas/produtos'
    | '/admin/estatisticas/tempo-real'
    | '/admin/estatisticas/vendas'
    | '/admin/estatisticas/visitas'
    | '/admin/loja/filtros'
    | '/admin/loja/menus'
    | '/admin/loja/paginas'
    | '/admin/loja/redes-sociais'
    | '/admin/marketing/captura-leads'
    | '/admin/marketing/compre-junto'
    | '/admin/marketing/grupo-vip'
    | '/admin/marketing/perguntas-avaliacoes'
    | '/admin/marketing/video-commerce'
    | '/admin/produtos/$id'
    | '/admin/produtos/categorias'
    | '/admin/produtos/tabela-precos'
    | '/admin/temas/sucesso'
    | '/api/public/host-debug'
    | '/feed/$slug/meta.xml'
    | '/loja/$slug/busca'
    | '/loja/$slug/rastreio'
    | '/loja/$slug/sobre'
    | '/loja/$slug/wishlist'
    | '/lovable/email/suppression'
    | '/admin/configuracoes/'
    | '/admin/estatisticas/'
    | '/admin/marketing/'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/admin/loja/layout/editar'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/pagina/$pageSlug'
    | '/loja/$slug/produto/$productSlug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/lovable/email/transactional/send-internal'
    | '/admin/loja/layout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/funcionalidades'
    | '/login'
    | '/painel'
    | '/precos'
    | '/preview-dark'
    | '/privacidade'
    | '/recuperar-senha'
    | '/reset-password'
    | '/termos'
    | '/unsubscribe'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/dashboard'
    | '/admin/descontos'
    | '/admin/financeiro'
    | '/admin/home-video'
    | '/admin/pedidos'
    | '/admin/perguntas'
    | '/admin/personalizar-loja'
    | '/admin/plano'
    | '/admin/temas'
    | '/admin/vendas'
    | '/api/virtual-try-on'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/hooks/cart-recovery'
    | '/hooks/cleanup-orphan-stores'
    | '/superadmin/clientes'
    | '/superadmin/lojas'
    | '/superadmin/metricas'
    | '/temas/$slug'
    | '/vip/$slug'
    | '/admin'
    | '/superadmin'
    | '/temas'
    | '/admin/clientes/avaliacoes'
    | '/admin/clientes/leads'
    | '/admin/configuracoes/contato'
    | '/admin/configuracoes/dominios'
    | '/admin/configuracoes/equipe'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/politicas'
    | '/admin/configuracoes/usuarios'
    | '/admin/configuracoes/whatsapp'
    | '/admin/descontos/cupons'
    | '/admin/descontos/frete-gratis'
    | '/admin/descontos/promocoes'
    | '/admin/estatisticas/produtos'
    | '/admin/estatisticas/tempo-real'
    | '/admin/estatisticas/vendas'
    | '/admin/estatisticas/visitas'
    | '/admin/loja/filtros'
    | '/admin/loja/menus'
    | '/admin/loja/paginas'
    | '/admin/loja/redes-sociais'
    | '/admin/marketing/captura-leads'
    | '/admin/marketing/compre-junto'
    | '/admin/marketing/grupo-vip'
    | '/admin/marketing/perguntas-avaliacoes'
    | '/admin/marketing/video-commerce'
    | '/admin/produtos/$id'
    | '/admin/produtos/categorias'
    | '/admin/produtos/tabela-precos'
    | '/admin/temas/sucesso'
    | '/api/public/host-debug'
    | '/feed/$slug/meta.xml'
    | '/loja/$slug/busca'
    | '/loja/$slug/rastreio'
    | '/loja/$slug/sobre'
    | '/loja/$slug/wishlist'
    | '/lovable/email/suppression'
    | '/admin/configuracoes'
    | '/admin/estatisticas'
    | '/admin/marketing'
    | '/admin/produtos'
    | '/loja/$slug'
    | '/admin/loja/layout/editar'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/pagina/$pageSlug'
    | '/loja/$slug/produto/$productSlug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/lovable/email/transactional/send-internal'
    | '/admin/loja/layout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/funcionalidades'
    | '/login'
    | '/painel'
    | '/precos'
    | '/preview-dark'
    | '/privacidade'
    | '/recuperar-senha'
    | '/reset-password'
    | '/superadmin'
    | '/termos'
    | '/unsubscribe'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/descontos'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/home-video'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/perguntas'
    | '/admin/personalizar-loja'
    | '/admin/plano'
    | '/admin/temas'
    | '/admin/vendas'
    | '/api/virtual-try-on'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/hooks/cart-recovery'
    | '/hooks/cleanup-orphan-stores'
    | '/loja/$slug'
    | '/superadmin/clientes'
    | '/superadmin/lojas'
    | '/superadmin/metricas'
    | '/temas/$slug'
    | '/vip/$slug'
    | '/admin/'
    | '/superadmin/'
    | '/temas/'
    | '/admin/clientes/avaliacoes'
    | '/admin/clientes/leads'
    | '/admin/configuracoes/contato'
    | '/admin/configuracoes/dominios'
    | '/admin/configuracoes/equipe'
    | '/admin/configuracoes/pagamentos'
    | '/admin/configuracoes/politicas'
    | '/admin/configuracoes/usuarios'
    | '/admin/configuracoes/whatsapp'
    | '/admin/descontos/cupons'
    | '/admin/descontos/frete-gratis'
    | '/admin/descontos/promocoes'
    | '/admin/estatisticas/produtos'
    | '/admin/estatisticas/tempo-real'
    | '/admin/estatisticas/vendas'
    | '/admin/estatisticas/visitas'
    | '/admin/loja/filtros'
    | '/admin/loja/menus'
    | '/admin/loja/paginas'
    | '/admin/loja/redes-sociais'
    | '/admin/marketing/captura-leads'
    | '/admin/marketing/compre-junto'
    | '/admin/marketing/grupo-vip'
    | '/admin/marketing/perguntas-avaliacoes'
    | '/admin/marketing/video-commerce'
    | '/admin/produtos/$id'
    | '/admin/produtos/categorias'
    | '/admin/produtos/tabela-precos'
    | '/admin/temas/sucesso'
    | '/api/public/host-debug'
    | '/feed/$slug/meta.xml'
    | '/loja/$slug/busca'
    | '/loja/$slug/rastreio'
    | '/loja/$slug/sobre'
    | '/loja/$slug/wishlist'
    | '/lovable/email/suppression'
    | '/admin/configuracoes/'
    | '/admin/estatisticas/'
    | '/admin/marketing/'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/admin/loja/layout/editar'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/pagina/$pageSlug'
    | '/loja/$slug/produto/$productSlug'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/lovable/email/transactional/send-internal'
    | '/admin/loja/layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  PrecosRoute: typeof PrecosRoute
  PreviewDarkRoute: typeof PreviewDarkRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TermosRoute: typeof TermosRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiVirtualTryOnRoute: typeof ApiVirtualTryOnRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  HooksCartRecoveryRoute: typeof HooksCartRecoveryRoute
  HooksCleanupOrphanStoresRoute: typeof HooksCleanupOrphanStoresRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
  TemasSlugRoute: typeof TemasSlugRoute
  VipSlugRoute: typeof VipSlugRoute
  TemasIndexRoute: typeof TemasIndexRoute
  ApiPublicHostDebugRoute: typeof ApiPublicHostDebugRoute
  FeedSlugMetaDotxmlRoute: typeof FeedSlugMetaDotxmlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  LovableEmailTransactionalSendInternalRoute: typeof LovableEmailTransactionalSendInternalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-dark': {
      id: '/preview-dark'
      path: '/preview-dark'
      fullPath: '/preview-dark'
      preLoaderRoute: typeof PreviewDarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/': {
      id: '/temas/'
      path: '/temas'
      fullPath: '/temas/'
      preLoaderRoute: typeof TemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vip/$slug': {
      id: '/vip/$slug'
      path: '/vip/$slug'
      fullPath: '/vip/$slug'
      preLoaderRoute: typeof VipSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/$slug': {
      id: '/temas/$slug'
      path: '/temas/$slug'
      fullPath: '/temas/$slug'
      preLoaderRoute: typeof TemasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/metricas': {
      id: '/superadmin/metricas'
      path: '/metricas'
      fullPath: '/superadmin/metricas'
      preLoaderRoute: typeof SuperadminMetricasRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/lojas': {
      id: '/superadmin/lojas'
      path: '/lojas'
      fullPath: '/superadmin/lojas'
      preLoaderRoute: typeof SuperadminLojasRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/clientes': {
      id: '/superadmin/clientes'
      path: '/clientes'
      fullPath: '/superadmin/clientes'
      preLoaderRoute: typeof SuperadminClientesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/cleanup-orphan-stores': {
      id: '/hooks/cleanup-orphan-stores'
      path: '/hooks/cleanup-orphan-stores'
      fullPath: '/hooks/cleanup-orphan-stores'
      preLoaderRoute: typeof HooksCleanupOrphanStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/cart-recovery': {
      id: '/hooks/cart-recovery'
      path: '/hooks/cart-recovery'
      fullPath: '/hooks/cart-recovery'
      preLoaderRoute: typeof HooksCartRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/virtual-try-on': {
      id: '/api/virtual-try-on'
      path: '/api/virtual-try-on'
      fullPath: '/api/virtual-try-on'
      preLoaderRoute: typeof ApiVirtualTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/temas': {
      id: '/admin/temas'
      path: '/temas'
      fullPath: '/admin/temas'
      preLoaderRoute: typeof AdminTemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plano': {
      id: '/admin/plano'
      path: '/plano'
      fullPath: '/admin/plano'
      preLoaderRoute: typeof AdminPlanoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personalizar-loja': {
      id: '/admin/personalizar-loja'
      path: '/personalizar-loja'
      fullPath: '/admin/personalizar-loja'
      preLoaderRoute: typeof AdminPersonalizarLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perguntas': {
      id: '/admin/perguntas'
      path: '/perguntas'
      fullPath: '/admin/perguntas'
      preLoaderRoute: typeof AdminPerguntasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home-video': {
      id: '/admin/home-video'
      path: '/home-video'
      fullPath: '/admin/home-video'
      preLoaderRoute: typeof AdminHomeVideoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estatisticas': {
      id: '/admin/estatisticas'
      path: '/estatisticas'
      fullPath: '/admin/estatisticas'
      preLoaderRoute: typeof AdminEstatisticasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/descontos': {
      id: '/admin/descontos'
      path: '/descontos'
      fullPath: '/admin/descontos'
      preLoaderRoute: typeof AdminDescontosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/': {
      id: '/admin/marketing/'
      path: '/'
      fullPath: '/admin/marketing/'
      preLoaderRoute: typeof AdminMarketingIndexRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/estatisticas/': {
      id: '/admin/estatisticas/'
      path: '/'
      fullPath: '/admin/estatisticas/'
      preLoaderRoute: typeof AdminEstatisticasIndexRouteImport
      parentRoute: typeof AdminEstatisticasRoute
    }
    '/admin/configuracoes/': {
      id: '/admin/configuracoes/'
      path: '/'
      fullPath: '/admin/configuracoes/'
      preLoaderRoute: typeof AdminConfiguracoesIndexRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug/wishlist': {
      id: '/loja/$slug/wishlist'
      path: '/wishlist'
      fullPath: '/loja/$slug/wishlist'
      preLoaderRoute: typeof LojaSlugWishlistRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/sobre': {
      id: '/loja/$slug/sobre'
      path: '/sobre'
      fullPath: '/loja/$slug/sobre'
      preLoaderRoute: typeof LojaSlugSobreRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/rastreio': {
      id: '/loja/$slug/rastreio'
      path: '/rastreio'
      fullPath: '/loja/$slug/rastreio'
      preLoaderRoute: typeof LojaSlugRastreioRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/busca': {
      id: '/loja/$slug/busca'
      path: '/busca'
      fullPath: '/loja/$slug/busca'
      preLoaderRoute: typeof LojaSlugBuscaRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/feed/$slug/meta.xml': {
      id: '/feed/$slug/meta.xml'
      path: '/feed/$slug/meta.xml'
      fullPath: '/feed/$slug/meta.xml'
      preLoaderRoute: typeof FeedSlugMetaDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/host-debug': {
      id: '/api/public/host-debug'
      path: '/api/public/host-debug'
      fullPath: '/api/public/host-debug'
      preLoaderRoute: typeof ApiPublicHostDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/temas/sucesso': {
      id: '/admin/temas/sucesso'
      path: '/sucesso'
      fullPath: '/admin/temas/sucesso'
      preLoaderRoute: typeof AdminTemasSucessoRouteImport
      parentRoute: typeof AdminTemasRoute
    }
    '/admin/produtos/tabela-precos': {
      id: '/admin/produtos/tabela-precos'
      path: '/produtos/tabela-precos'
      fullPath: '/admin/produtos/tabela-precos'
      preLoaderRoute: typeof AdminProdutosTabelaPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/categorias': {
      id: '/admin/produtos/categorias'
      path: '/produtos/categorias'
      fullPath: '/admin/produtos/categorias'
      preLoaderRoute: typeof AdminProdutosCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/video-commerce': {
      id: '/admin/marketing/video-commerce'
      path: '/video-commerce'
      fullPath: '/admin/marketing/video-commerce'
      preLoaderRoute: typeof AdminMarketingVideoCommerceRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/perguntas-avaliacoes': {
      id: '/admin/marketing/perguntas-avaliacoes'
      path: '/perguntas-avaliacoes'
      fullPath: '/admin/marketing/perguntas-avaliacoes'
      preLoaderRoute: typeof AdminMarketingPerguntasAvaliacoesRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/grupo-vip': {
      id: '/admin/marketing/grupo-vip'
      path: '/grupo-vip'
      fullPath: '/admin/marketing/grupo-vip'
      preLoaderRoute: typeof AdminMarketingGrupoVipRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/compre-junto': {
      id: '/admin/marketing/compre-junto'
      path: '/compre-junto'
      fullPath: '/admin/marketing/compre-junto'
      preLoaderRoute: typeof AdminMarketingCompreJuntoRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/marketing/captura-leads': {
      id: '/admin/marketing/captura-leads'
      path: '/captura-leads'
      fullPath: '/admin/marketing/captura-leads'
      preLoaderRoute: typeof AdminMarketingCapturaLeadsRouteImport
      parentRoute: typeof AdminMarketingRoute
    }
    '/admin/loja/redes-sociais': {
      id: '/admin/loja/redes-sociais'
      path: '/loja/redes-sociais'
      fullPath: '/admin/loja/redes-sociais'
      preLoaderRoute: typeof AdminLojaRedesSociaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja/paginas': {
      id: '/admin/loja/paginas'
      path: '/loja/paginas'
      fullPath: '/admin/loja/paginas'
      preLoaderRoute: typeof AdminLojaPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja/menus': {
      id: '/admin/loja/menus'
      path: '/loja/menus'
      fullPath: '/admin/loja/menus'
      preLoaderRoute: typeof AdminLojaMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja/filtros': {
      id: '/admin/loja/filtros'
      path: '/loja/filtros'
      fullPath: '/admin/loja/filtros'
      preLoaderRoute: typeof AdminLojaFiltrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estatisticas/visitas': {
      id: '/admin/estatisticas/visitas'
      path: '/visitas'
      fullPath: '/admin/estatisticas/visitas'
      preLoaderRoute: typeof AdminEstatisticasVisitasRouteImport
      parentRoute: typeof AdminEstatisticasRoute
    }
    '/admin/estatisticas/vendas': {
      id: '/admin/estatisticas/vendas'
      path: '/vendas'
      fullPath: '/admin/estatisticas/vendas'
      preLoaderRoute: typeof AdminEstatisticasVendasRouteImport
      parentRoute: typeof AdminEstatisticasRoute
    }
    '/admin/estatisticas/tempo-real': {
      id: '/admin/estatisticas/tempo-real'
      path: '/tempo-real'
      fullPath: '/admin/estatisticas/tempo-real'
      preLoaderRoute: typeof AdminEstatisticasTempoRealRouteImport
      parentRoute: typeof AdminEstatisticasRoute
    }
    '/admin/estatisticas/produtos': {
      id: '/admin/estatisticas/produtos'
      path: '/produtos'
      fullPath: '/admin/estatisticas/produtos'
      preLoaderRoute: typeof AdminEstatisticasProdutosRouteImport
      parentRoute: typeof AdminEstatisticasRoute
    }
    '/admin/descontos/promocoes': {
      id: '/admin/descontos/promocoes'
      path: '/promocoes'
      fullPath: '/admin/descontos/promocoes'
      preLoaderRoute: typeof AdminDescontosPromocoesRouteImport
      parentRoute: typeof AdminDescontosRoute
    }
    '/admin/descontos/frete-gratis': {
      id: '/admin/descontos/frete-gratis'
      path: '/frete-gratis'
      fullPath: '/admin/descontos/frete-gratis'
      preLoaderRoute: typeof AdminDescontosFreteGratisRouteImport
      parentRoute: typeof AdminDescontosRoute
    }
    '/admin/descontos/cupons': {
      id: '/admin/descontos/cupons'
      path: '/cupons'
      fullPath: '/admin/descontos/cupons'
      preLoaderRoute: typeof AdminDescontosCuponsRouteImport
      parentRoute: typeof AdminDescontosRoute
    }
    '/admin/configuracoes/whatsapp': {
      id: '/admin/configuracoes/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/configuracoes/whatsapp'
      preLoaderRoute: typeof AdminConfiguracoesWhatsappRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/usuarios': {
      id: '/admin/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/admin/configuracoes/usuarios'
      preLoaderRoute: typeof AdminConfiguracoesUsuariosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/politicas': {
      id: '/admin/configuracoes/politicas'
      path: '/politicas'
      fullPath: '/admin/configuracoes/politicas'
      preLoaderRoute: typeof AdminConfiguracoesPoliticasRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/pagamentos': {
      id: '/admin/configuracoes/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/configuracoes/pagamentos'
      preLoaderRoute: typeof AdminConfiguracoesPagamentosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/equipe': {
      id: '/admin/configuracoes/equipe'
      path: '/equipe'
      fullPath: '/admin/configuracoes/equipe'
      preLoaderRoute: typeof AdminConfiguracoesEquipeRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/dominios': {
      id: '/admin/configuracoes/dominios'
      path: '/dominios'
      fullPath: '/admin/configuracoes/dominios'
      preLoaderRoute: typeof AdminConfiguracoesDominiosRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/configuracoes/contato': {
      id: '/admin/configuracoes/contato'
      path: '/contato'
      fullPath: '/admin/configuracoes/contato'
      preLoaderRoute: typeof AdminConfiguracoesContatoRouteImport
      parentRoute: typeof AdminConfiguracoesRoute
    }
    '/admin/clientes/leads': {
      id: '/admin/clientes/leads'
      path: '/leads'
      fullPath: '/admin/clientes/leads'
      preLoaderRoute: typeof AdminClientesLeadsRouteImport
      parentRoute: typeof AdminClientesRoute
    }
    '/admin/clientes/avaliacoes': {
      id: '/admin/clientes/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/clientes/avaliacoes'
      preLoaderRoute: typeof AdminClientesAvaliacoesRouteImport
      parentRoute: typeof AdminClientesRoute
    }
    '/admin/loja/layout/': {
      id: '/admin/loja/layout/'
      path: '/loja/layout'
      fullPath: '/admin/loja/layout/'
      preLoaderRoute: typeof AdminLojaLayoutIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send-internal': {
      id: '/lovable/email/transactional/send-internal'
      path: '/lovable/email/transactional/send-internal'
      fullPath: '/lovable/email/transactional/send-internal'
      preLoaderRoute: typeof LovableEmailTransactionalSendInternalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug/produto/$productSlug': {
      id: '/loja/$slug/produto/$productSlug'
      path: '/produto/$productSlug'
      fullPath: '/loja/$slug/produto/$productSlug'
      preLoaderRoute: typeof LojaSlugProdutoProductSlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/pagina/$pageSlug': {
      id: '/loja/$slug/pagina/$pageSlug'
      path: '/pagina/$pageSlug'
      fullPath: '/loja/$slug/pagina/$pageSlug'
      preLoaderRoute: typeof LojaSlugPaginaPageSlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/categoria/$categorySlug': {
      id: '/loja/$slug/categoria/$categorySlug'
      path: '/categoria/$categorySlug'
      fullPath: '/loja/$slug/categoria/$categorySlug'
      preLoaderRoute: typeof LojaSlugCategoriaCategorySlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/admin/loja/layout/editar': {
      id: '/admin/loja/layout/editar'
      path: '/loja/layout/editar'
      fullPath: '/admin/loja/layout/editar'
      preLoaderRoute: typeof AdminLojaLayoutEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminClientesRouteChildren {
  AdminClientesAvaliacoesRoute: typeof AdminClientesAvaliacoesRoute
  AdminClientesLeadsRoute: typeof AdminClientesLeadsRoute
}

const AdminClientesRouteChildren: AdminClientesRouteChildren = {
  AdminClientesAvaliacoesRoute: AdminClientesAvaliacoesRoute,
  AdminClientesLeadsRoute: AdminClientesLeadsRoute,
}

const AdminClientesRouteWithChildren = AdminClientesRoute._addFileChildren(
  AdminClientesRouteChildren,
)

interface AdminConfiguracoesRouteChildren {
  AdminConfiguracoesContatoRoute: typeof AdminConfiguracoesContatoRoute
  AdminConfiguracoesDominiosRoute: typeof AdminConfiguracoesDominiosRoute
  AdminConfiguracoesEquipeRoute: typeof AdminConfiguracoesEquipeRoute
  AdminConfiguracoesPagamentosRoute: typeof AdminConfiguracoesPagamentosRoute
  AdminConfiguracoesPoliticasRoute: typeof AdminConfiguracoesPoliticasRoute
  AdminConfiguracoesUsuariosRoute: typeof AdminConfiguracoesUsuariosRoute
  AdminConfiguracoesWhatsappRoute: typeof AdminConfiguracoesWhatsappRoute
  AdminConfiguracoesIndexRoute: typeof AdminConfiguracoesIndexRoute
}

const AdminConfiguracoesRouteChildren: AdminConfiguracoesRouteChildren = {
  AdminConfiguracoesContatoRoute: AdminConfiguracoesContatoRoute,
  AdminConfiguracoesDominiosRoute: AdminConfiguracoesDominiosRoute,
  AdminConfiguracoesEquipeRoute: AdminConfiguracoesEquipeRoute,
  AdminConfiguracoesPagamentosRoute: AdminConfiguracoesPagamentosRoute,
  AdminConfiguracoesPoliticasRoute: AdminConfiguracoesPoliticasRoute,
  AdminConfiguracoesUsuariosRoute: AdminConfiguracoesUsuariosRoute,
  AdminConfiguracoesWhatsappRoute: AdminConfiguracoesWhatsappRoute,
  AdminConfiguracoesIndexRoute: AdminConfiguracoesIndexRoute,
}

const AdminConfiguracoesRouteWithChildren =
  AdminConfiguracoesRoute._addFileChildren(AdminConfiguracoesRouteChildren)

interface AdminDescontosRouteChildren {
  AdminDescontosCuponsRoute: typeof AdminDescontosCuponsRoute
  AdminDescontosFreteGratisRoute: typeof AdminDescontosFreteGratisRoute
  AdminDescontosPromocoesRoute: typeof AdminDescontosPromocoesRoute
}

const AdminDescontosRouteChildren: AdminDescontosRouteChildren = {
  AdminDescontosCuponsRoute: AdminDescontosCuponsRoute,
  AdminDescontosFreteGratisRoute: AdminDescontosFreteGratisRoute,
  AdminDescontosPromocoesRoute: AdminDescontosPromocoesRoute,
}

const AdminDescontosRouteWithChildren = AdminDescontosRoute._addFileChildren(
  AdminDescontosRouteChildren,
)

interface AdminEstatisticasRouteChildren {
  AdminEstatisticasProdutosRoute: typeof AdminEstatisticasProdutosRoute
  AdminEstatisticasTempoRealRoute: typeof AdminEstatisticasTempoRealRoute
  AdminEstatisticasVendasRoute: typeof AdminEstatisticasVendasRoute
  AdminEstatisticasVisitasRoute: typeof AdminEstatisticasVisitasRoute
  AdminEstatisticasIndexRoute: typeof AdminEstatisticasIndexRoute
}

const AdminEstatisticasRouteChildren: AdminEstatisticasRouteChildren = {
  AdminEstatisticasProdutosRoute: AdminEstatisticasProdutosRoute,
  AdminEstatisticasTempoRealRoute: AdminEstatisticasTempoRealRoute,
  AdminEstatisticasVendasRoute: AdminEstatisticasVendasRoute,
  AdminEstatisticasVisitasRoute: AdminEstatisticasVisitasRoute,
  AdminEstatisticasIndexRoute: AdminEstatisticasIndexRoute,
}

const AdminEstatisticasRouteWithChildren =
  AdminEstatisticasRoute._addFileChildren(AdminEstatisticasRouteChildren)

interface AdminMarketingRouteChildren {
  AdminMarketingCapturaLeadsRoute: typeof AdminMarketingCapturaLeadsRoute
  AdminMarketingCompreJuntoRoute: typeof AdminMarketingCompreJuntoRoute
  AdminMarketingGrupoVipRoute: typeof AdminMarketingGrupoVipRoute
  AdminMarketingPerguntasAvaliacoesRoute: typeof AdminMarketingPerguntasAvaliacoesRoute
  AdminMarketingVideoCommerceRoute: typeof AdminMarketingVideoCommerceRoute
  AdminMarketingIndexRoute: typeof AdminMarketingIndexRoute
}

const AdminMarketingRouteChildren: AdminMarketingRouteChildren = {
  AdminMarketingCapturaLeadsRoute: AdminMarketingCapturaLeadsRoute,
  AdminMarketingCompreJuntoRoute: AdminMarketingCompreJuntoRoute,
  AdminMarketingGrupoVipRoute: AdminMarketingGrupoVipRoute,
  AdminMarketingPerguntasAvaliacoesRoute:
    AdminMarketingPerguntasAvaliacoesRoute,
  AdminMarketingVideoCommerceRoute: AdminMarketingVideoCommerceRoute,
  AdminMarketingIndexRoute: AdminMarketingIndexRoute,
}

const AdminMarketingRouteWithChildren = AdminMarketingRoute._addFileChildren(
  AdminMarketingRouteChildren,
)

interface AdminTemasRouteChildren {
  AdminTemasSucessoRoute: typeof AdminTemasSucessoRoute
}

const AdminTemasRouteChildren: AdminTemasRouteChildren = {
  AdminTemasSucessoRoute: AdminTemasSucessoRoute,
}

const AdminTemasRouteWithChildren = AdminTemasRoute._addFileChildren(
  AdminTemasRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRouteWithChildren
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDescontosRoute: typeof AdminDescontosRouteWithChildren
  AdminEstatisticasRoute: typeof AdminEstatisticasRouteWithChildren
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminHomeVideoRoute: typeof AdminHomeVideoRoute
  AdminMarketingRoute: typeof AdminMarketingRouteWithChildren
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPerguntasRoute: typeof AdminPerguntasRoute
  AdminPersonalizarLojaRoute: typeof AdminPersonalizarLojaRoute
  AdminPlanoRoute: typeof AdminPlanoRoute
  AdminTemasRoute: typeof AdminTemasRouteWithChildren
  AdminVendasRoute: typeof AdminVendasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLojaFiltrosRoute: typeof AdminLojaFiltrosRoute
  AdminLojaMenusRoute: typeof AdminLojaMenusRoute
  AdminLojaPaginasRoute: typeof AdminLojaPaginasRoute
  AdminLojaRedesSociaisRoute: typeof AdminLojaRedesSociaisRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosCategoriasRoute: typeof AdminProdutosCategoriasRoute
  AdminProdutosTabelaPrecosRoute: typeof AdminProdutosTabelaPrecosRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
  AdminLojaLayoutEditarRoute: typeof AdminLojaLayoutEditarRoute
  AdminLojaLayoutIndexRoute: typeof AdminLojaLayoutIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRouteWithChildren,
  AdminConfiguracoesRoute: AdminConfiguracoesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDescontosRoute: AdminDescontosRouteWithChildren,
  AdminEstatisticasRoute: AdminEstatisticasRouteWithChildren,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminHomeVideoRoute: AdminHomeVideoRoute,
  AdminMarketingRoute: AdminMarketingRouteWithChildren,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPerguntasRoute: AdminPerguntasRoute,
  AdminPersonalizarLojaRoute: AdminPersonalizarLojaRoute,
  AdminPlanoRoute: AdminPlanoRoute,
  AdminTemasRoute: AdminTemasRouteWithChildren,
  AdminVendasRoute: AdminVendasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLojaFiltrosRoute: AdminLojaFiltrosRoute,
  AdminLojaMenusRoute: AdminLojaMenusRoute,
  AdminLojaPaginasRoute: AdminLojaPaginasRoute,
  AdminLojaRedesSociaisRoute: AdminLojaRedesSociaisRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosCategoriasRoute: AdminProdutosCategoriasRoute,
  AdminProdutosTabelaPrecosRoute: AdminProdutosTabelaPrecosRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
  AdminLojaLayoutEditarRoute: AdminLojaLayoutEditarRoute,
  AdminLojaLayoutIndexRoute: AdminLojaLayoutIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperadminRouteChildren {
  SuperadminClientesRoute: typeof SuperadminClientesRoute
  SuperadminLojasRoute: typeof SuperadminLojasRoute
  SuperadminMetricasRoute: typeof SuperadminMetricasRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminClientesRoute: SuperadminClientesRoute,
  SuperadminLojasRoute: SuperadminLojasRoute,
  SuperadminMetricasRoute: SuperadminMetricasRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface LojaSlugRouteChildren {
  LojaSlugBuscaRoute: typeof LojaSlugBuscaRoute
  LojaSlugRastreioRoute: typeof LojaSlugRastreioRoute
  LojaSlugSobreRoute: typeof LojaSlugSobreRoute
  LojaSlugWishlistRoute: typeof LojaSlugWishlistRoute
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
  LojaSlugCategoriaCategorySlugRoute: typeof LojaSlugCategoriaCategorySlugRoute
  LojaSlugPaginaPageSlugRoute: typeof LojaSlugPaginaPageSlugRoute
  LojaSlugProdutoProductSlugRoute: typeof LojaSlugProdutoProductSlugRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugBuscaRoute: LojaSlugBuscaRoute,
  LojaSlugRastreioRoute: LojaSlugRastreioRoute,
  LojaSlugSobreRoute: LojaSlugSobreRoute,
  LojaSlugWishlistRoute: LojaSlugWishlistRoute,
  LojaSlugIndexRoute: LojaSlugIndexRoute,
  LojaSlugCategoriaCategorySlugRoute: LojaSlugCategoriaCategorySlugRoute,
  LojaSlugPaginaPageSlugRoute: LojaSlugPaginaPageSlugRoute,
  LojaSlugProdutoProductSlugRoute: LojaSlugProdutoProductSlugRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  PrecosRoute: PrecosRoute,
  PreviewDarkRoute: PreviewDarkRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TermosRoute: TermosRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiVirtualTryOnRoute: ApiVirtualTryOnRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  HooksCartRecoveryRoute: HooksCartRecoveryRoute,
  HooksCleanupOrphanStoresRoute: HooksCleanupOrphanStoresRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
  TemasSlugRoute: TemasSlugRoute,
  VipSlugRoute: VipSlugRoute,
  TemasIndexRoute: TemasIndexRoute,
  ApiPublicHostDebugRoute: ApiPublicHostDebugRoute,
  FeedSlugMetaDotxmlRoute: FeedSlugMetaDotxmlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  LovableEmailTransactionalSendInternalRoute:
    LovableEmailTransactionalSendInternalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
