/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PreviewDarkRouteImport } from './routes/preview-dark'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionalidadesRouteImport } from './routes/funcionalidades'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemasIndexRouteImport } from './routes/temas.index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TemasSlugRouteImport } from './routes/temas.$slug'
import { Route as SuperadminTemasRouteImport } from './routes/superadmin.temas'
import { Route as SuperadminLojasRouteImport } from './routes/superadmin.lojas'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as HooksCleanupOrphanStoresRouteImport } from './routes/hooks/cleanup-orphan-stores'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminTemasRouteImport } from './routes/admin.temas'
import { Route as AdminPlanoRouteImport } from './routes/admin.plano'
import { Route as AdminDescontosRouteImport } from './routes/admin.descontos'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as LojaSlugIndexRouteImport } from './routes/loja.$slug.index'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as LojaSlugWishlistRouteImport } from './routes/loja.$slug.wishlist'
import { Route as LojaSlugBuscaRouteImport } from './routes/loja.$slug.busca'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as LojaSlugProdutoProductSlugRouteImport } from './routes/loja.$slug.produto.$productSlug'
import { Route as LojaSlugCategoriaCategorySlugRouteImport } from './routes/loja.$slug.categoria.$categorySlug'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDarkRoute = PreviewDarkRouteImport.update({
  id: '/preview-dark',
  path: '/preview-dark',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionalidadesRoute = FuncionalidadesRouteImport.update({
  id: '/funcionalidades',
  path: '/funcionalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasIndexRoute = TemasIndexRouteImport.update({
  id: '/temas/',
  path: '/temas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TemasSlugRoute = TemasSlugRouteImport.update({
  id: '/temas/$slug',
  path: '/temas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTemasRoute = SuperadminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLojasRoute = SuperadminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => SuperadminRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksCleanupOrphanStoresRoute =
  HooksCleanupOrphanStoresRouteImport.update({
    id: '/hooks/cleanup-orphan-stores',
    path: '/hooks/cleanup-orphan-stores',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemasRoute = AdminTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanoRoute = AdminPlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDescontosRoute = AdminDescontosRouteImport.update({
  id: '/descontos',
  path: '/descontos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugIndexRoute = LojaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LojaSlugRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugWishlistRoute = LojaSlugWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => LojaSlugRoute,
} as any)
const LojaSlugBuscaRoute = LojaSlugBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => LojaSlugRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const LojaSlugProdutoProductSlugRoute =
  LojaSlugProdutoProductSlugRouteImport.update({
    id: '/produto/$productSlug',
    path: '/produto/$productSlug',
    getParentRoute: () => LojaSlugRoute,
  } as any)
const LojaSlugCategoriaCategorySlugRoute =
  LojaSlugCategoriaCategorySlugRouteImport.update({
    id: '/categoria/$categorySlug',
    path: '/categoria/$categorySlug',
    getParentRoute: () => LojaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/preview-dark': typeof PreviewDarkRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/descontos': typeof AdminDescontosRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/temas': typeof AdminTemasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/hooks/cleanup-orphan-stores': typeof HooksCleanupOrphanStoresRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/superadmin/lojas': typeof SuperadminLojasRoute
  '/superadmin/temas': typeof SuperadminTemasRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/temas/': typeof TemasIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/loja/$slug/busca': typeof LojaSlugBuscaRoute
  '/loja/$slug/wishlist': typeof LojaSlugWishlistRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/preview-dark': typeof PreviewDarkRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/descontos': typeof AdminDescontosRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/temas': typeof AdminTemasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/hooks/cleanup-orphan-stores': typeof HooksCleanupOrphanStoresRoute
  '/superadmin/lojas': typeof SuperadminLojasRoute
  '/superadmin/temas': typeof SuperadminTemasRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/temas': typeof TemasIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/loja/$slug/busca': typeof LojaSlugBuscaRoute
  '/loja/$slug/wishlist': typeof LojaSlugWishlistRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
  '/loja/$slug': typeof LojaSlugIndexRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/funcionalidades': typeof FuncionalidadesRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/precos': typeof PrecosRoute
  '/preview-dark': typeof PreviewDarkRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/descontos': typeof AdminDescontosRoute
  '/admin/plano': typeof AdminPlanoRoute
  '/admin/temas': typeof AdminTemasRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/hooks/cleanup-orphan-stores': typeof HooksCleanupOrphanStoresRoute
  '/loja/$slug': typeof LojaSlugRouteWithChildren
  '/superadmin/lojas': typeof SuperadminLojasRoute
  '/superadmin/temas': typeof SuperadminTemasRoute
  '/temas/$slug': typeof TemasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/temas/': typeof TemasIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/loja/$slug/busca': typeof LojaSlugBuscaRoute
  '/loja/$slug/wishlist': typeof LojaSlugWishlistRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
  '/loja/$slug/': typeof LojaSlugIndexRoute
  '/loja/$slug/categoria/$categorySlug': typeof LojaSlugCategoriaCategorySlugRoute
  '/loja/$slug/produto/$productSlug': typeof LojaSlugProdutoProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/funcionalidades'
    | '/login'
    | '/painel'
    | '/precos'
    | '/preview-dark'
    | '/recuperar-senha'
    | '/reset-password'
    | '/superadmin'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/descontos'
    | '/admin/plano'
    | '/admin/temas'
    | '/checkout/return'
    | '/hooks/cleanup-orphan-stores'
    | '/loja/$slug'
    | '/superadmin/lojas'
    | '/superadmin/temas'
    | '/temas/$slug'
    | '/admin/'
    | '/superadmin/'
    | '/temas/'
    | '/admin/produtos/$id'
    | '/loja/$slug/busca'
    | '/loja/$slug/wishlist'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/produto/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/funcionalidades'
    | '/login'
    | '/painel'
    | '/precos'
    | '/preview-dark'
    | '/recuperar-senha'
    | '/reset-password'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/descontos'
    | '/admin/plano'
    | '/admin/temas'
    | '/checkout/return'
    | '/hooks/cleanup-orphan-stores'
    | '/superadmin/lojas'
    | '/superadmin/temas'
    | '/temas/$slug'
    | '/admin'
    | '/superadmin'
    | '/temas'
    | '/admin/produtos/$id'
    | '/loja/$slug/busca'
    | '/loja/$slug/wishlist'
    | '/admin/produtos'
    | '/loja/$slug'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/produto/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/funcionalidades'
    | '/login'
    | '/painel'
    | '/precos'
    | '/preview-dark'
    | '/recuperar-senha'
    | '/reset-password'
    | '/superadmin'
    | '/admin/avaliacoes'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/descontos'
    | '/admin/plano'
    | '/admin/temas'
    | '/checkout/return'
    | '/hooks/cleanup-orphan-stores'
    | '/loja/$slug'
    | '/superadmin/lojas'
    | '/superadmin/temas'
    | '/temas/$slug'
    | '/admin/'
    | '/superadmin/'
    | '/temas/'
    | '/admin/produtos/$id'
    | '/loja/$slug/busca'
    | '/loja/$slug/wishlist'
    | '/admin/produtos/'
    | '/loja/$slug/'
    | '/loja/$slug/categoria/$categorySlug'
    | '/loja/$slug/produto/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  FuncionalidadesRoute: typeof FuncionalidadesRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  PrecosRoute: typeof PrecosRoute
  PreviewDarkRoute: typeof PreviewDarkRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  HooksCleanupOrphanStoresRoute: typeof HooksCleanupOrphanStoresRoute
  LojaSlugRoute: typeof LojaSlugRouteWithChildren
  TemasSlugRoute: typeof TemasSlugRoute
  TemasIndexRoute: typeof TemasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-dark': {
      id: '/preview-dark'
      path: '/preview-dark'
      fullPath: '/preview-dark'
      preLoaderRoute: typeof PreviewDarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionalidades': {
      id: '/funcionalidades'
      path: '/funcionalidades'
      fullPath: '/funcionalidades'
      preLoaderRoute: typeof FuncionalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/': {
      id: '/temas/'
      path: '/temas'
      fullPath: '/temas/'
      preLoaderRoute: typeof TemasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/temas/$slug': {
      id: '/temas/$slug'
      path: '/temas/$slug'
      fullPath: '/temas/$slug'
      preLoaderRoute: typeof TemasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/temas': {
      id: '/superadmin/temas'
      path: '/temas'
      fullPath: '/superadmin/temas'
      preLoaderRoute: typeof SuperadminTemasRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/lojas': {
      id: '/superadmin/lojas'
      path: '/lojas'
      fullPath: '/superadmin/lojas'
      preLoaderRoute: typeof SuperadminLojasRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/cleanup-orphan-stores': {
      id: '/hooks/cleanup-orphan-stores'
      path: '/hooks/cleanup-orphan-stores'
      fullPath: '/hooks/cleanup-orphan-stores'
      preLoaderRoute: typeof HooksCleanupOrphanStoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/temas': {
      id: '/admin/temas'
      path: '/temas'
      fullPath: '/admin/temas'
      preLoaderRoute: typeof AdminTemasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plano': {
      id: '/admin/plano'
      path: '/plano'
      fullPath: '/admin/plano'
      preLoaderRoute: typeof AdminPlanoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/descontos': {
      id: '/admin/descontos'
      path: '/descontos'
      fullPath: '/admin/descontos'
      preLoaderRoute: typeof AdminDescontosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/': {
      id: '/loja/$slug/'
      path: '/'
      fullPath: '/loja/$slug/'
      preLoaderRoute: typeof LojaSlugIndexRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/wishlist': {
      id: '/loja/$slug/wishlist'
      path: '/wishlist'
      fullPath: '/loja/$slug/wishlist'
      preLoaderRoute: typeof LojaSlugWishlistRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/busca': {
      id: '/loja/$slug/busca'
      path: '/busca'
      fullPath: '/loja/$slug/busca'
      preLoaderRoute: typeof LojaSlugBuscaRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/loja/$slug/produto/$productSlug': {
      id: '/loja/$slug/produto/$productSlug'
      path: '/produto/$productSlug'
      fullPath: '/loja/$slug/produto/$productSlug'
      preLoaderRoute: typeof LojaSlugProdutoProductSlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
    '/loja/$slug/categoria/$categorySlug': {
      id: '/loja/$slug/categoria/$categorySlug'
      path: '/categoria/$categorySlug'
      fullPath: '/loja/$slug/categoria/$categorySlug'
      preLoaderRoute: typeof LojaSlugCategoriaCategorySlugRouteImport
      parentRoute: typeof LojaSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDescontosRoute: typeof AdminDescontosRoute
  AdminPlanoRoute: typeof AdminPlanoRoute
  AdminTemasRoute: typeof AdminTemasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDescontosRoute: AdminDescontosRoute,
  AdminPlanoRoute: AdminPlanoRoute,
  AdminTemasRoute: AdminTemasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperadminRouteChildren {
  SuperadminLojasRoute: typeof SuperadminLojasRoute
  SuperadminTemasRoute: typeof SuperadminTemasRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminLojasRoute: SuperadminLojasRoute,
  SuperadminTemasRoute: SuperadminTemasRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface LojaSlugRouteChildren {
  LojaSlugBuscaRoute: typeof LojaSlugBuscaRoute
  LojaSlugWishlistRoute: typeof LojaSlugWishlistRoute
  LojaSlugIndexRoute: typeof LojaSlugIndexRoute
  LojaSlugCategoriaCategorySlugRoute: typeof LojaSlugCategoriaCategorySlugRoute
  LojaSlugProdutoProductSlugRoute: typeof LojaSlugProdutoProductSlugRoute
}

const LojaSlugRouteChildren: LojaSlugRouteChildren = {
  LojaSlugBuscaRoute: LojaSlugBuscaRoute,
  LojaSlugWishlistRoute: LojaSlugWishlistRoute,
  LojaSlugIndexRoute: LojaSlugIndexRoute,
  LojaSlugCategoriaCategorySlugRoute: LojaSlugCategoriaCategorySlugRoute,
  LojaSlugProdutoProductSlugRoute: LojaSlugProdutoProductSlugRoute,
}

const LojaSlugRouteWithChildren = LojaSlugRoute._addFileChildren(
  LojaSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  FuncionalidadesRoute: FuncionalidadesRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  PrecosRoute: PrecosRoute,
  PreviewDarkRoute: PreviewDarkRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  CheckoutReturnRoute: CheckoutReturnRoute,
  HooksCleanupOrphanStoresRoute: HooksCleanupOrphanStoresRoute,
  LojaSlugRoute: LojaSlugRouteWithChildren,
  TemasSlugRoute: TemasSlugRoute,
  TemasIndexRoute: TemasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
