
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS show_price BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS product_type TEXT DEFAULT 'physical',
  ADD COLUMN IF NOT EXISTS seo_title TEXT,
  ADD COLUMN IF NOT EXISTS seo_description TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[],
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS url_slug TEXT,
  ADD COLUMN IF NOT EXISTS free_shipping BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_visible BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS featured_sections TEXT[];

NOTIFY pgrst, 'reload schema';
